<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PositionEchelonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('position_echelons')->delete();

        $positionEchelons = [
            //jabatan fungsional
            [
                'position_id' => 41,
                'echelon_id' => 5,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 45,
                'echelon_id' => 6,
                'available' => 3,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 45,
                'echelon_id' => 7,
                'available' => 6,
                'vertical_order' => 2,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 45,
                'echelon_id' => 8,
                'available' => 2,
                'vertical_order' => 3,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 47,
                'echelon_id' => 7,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 47,
                'echelon_id' => 8,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 47,
                'echelon_id' => 10,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 47,
                'echelon_id' => 11,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'position_id' => 47,
                'echelon_id' => 12,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'position_id' => 49,
                'echelon_id' => 6,
                'available' => 3,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 49,
                'echelon_id' => 7,
                'available' => 4,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 49,
                'echelon_id' => 8,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 194,
                'echelon_id' => 7,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 51,
                'echelon_id' => 7,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 51,
                'echelon_id' => 8,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 51,
                'echelon_id' => 10,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 51,
                'echelon_id' => 11,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'position_id' => 51,
                'echelon_id' => 12,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'position_id' => 52,
                'echelon_id' => 9,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 6,
            ],
            [
                'position_id' => 53,
                'echelon_id' => 6,
                'available' => 3,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 53,
                'echelon_id' => 7,
                'available' => 6,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 53,
                'echelon_id' => 8,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 55,
                'echelon_id' => 7,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 55,
                'echelon_id' => 8,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 55,
                'echelon_id' => 10,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 55,
                'echelon_id' => 11,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'position_id' => 55,
                'echelon_id' => 12,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'position_id' => 57,
                'echelon_id' => 9,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 6,
            ],
            [
                'position_id' => 58,
                'echelon_id' => 5,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 62,
                'echelon_id' => 6,
                'available' => 3,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 62,
                'echelon_id' => 7,
                'available' => 6,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 62,
                'echelon_id' => 8,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 64,
                'echelon_id' => 7,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 64,
                'echelon_id' => 8,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 64,
                'echelon_id' => 10,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 64,
                'echelon_id' => 11,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'position_id' => 64,
                'echelon_id' => 12,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'position_id' => 66,
                'echelon_id' => 6,
                'available' => 3,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 66,
                'echelon_id' => 7,
                'available' => 6,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 66,
                'echelon_id' => 8,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 69,
                'echelon_id' => 6,
                'available' => 3,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 69,
                'echelon_id' => 7,
                'available' => 6,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 69,
                'echelon_id' => 8,
                'available' => 3,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 71,
                'echelon_id' => 7,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 71,
                'echelon_id' => 8,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 71,
                'echelon_id' => 10,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 71,
                'echelon_id' => 11,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'position_id' => 71,
                'echelon_id' => 12,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'position_id' => 74,
                'echelon_id' => 5,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 79,
                'echelon_id' => 6,
                'available' => 3,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 79,
                'echelon_id' => 7,
                'available' => 6,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 79,
                'echelon_id' => 8,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 82,
                'echelon_id' => 7,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 82,
                'echelon_id' => 8,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 82,
                'echelon_id' => 10,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 82,
                'echelon_id' => 11,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'position_id' => 82,
                'echelon_id' => 12,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'position_id' => 84,
                'echelon_id' => 6,
                'available' => 3,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 84,
                'echelon_id' => 7,
                'available' => 6,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 84,
                'echelon_id' => 8,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 86,
                'echelon_id' => 9,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'position_id' => 87,
                'echelon_id' => 7,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 87,
                'echelon_id' => 8,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 87,
                'echelon_id' => 10,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 87,
                'echelon_id' => 11,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 87,
                'echelon_id' => 12,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'position_id' => 89,
                'echelon_id' => 6,
                'available' => 3,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 89,
                'echelon_id' => 7,
                'available' => 6,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 89,
                'echelon_id' => 8,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 91,
                'echelon_id' => 7,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 91,
                'echelon_id' => 8,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 91,
                'echelon_id' => 10,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 91,
                'echelon_id' => 11,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 91,
                'echelon_id' => 12,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'position_id' => 93,
                'echelon_id' => 6,
                'available' => 3,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 93,
                'echelon_id' => 7,
                'available' => 6,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 93,
                'echelon_id' => 8,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 95,
                'echelon_id' => 7,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 95,
                'echelon_id' => 8,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 95,
                'echelon_id' => 10,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 95,
                'echelon_id' => 11,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'position_id' => 95,
                'echelon_id' => 12,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'position_id' => 102,
                'echelon_id' => 7,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 102,
                'echelon_id' => 8,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 102,
                'echelon_id' => 10,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 102,
                'echelon_id' => 11,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'position_id' => 102,
                'echelon_id' => 12,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'position_id' => 136,
                'echelon_id' => 6,
                'available' => 4,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 136,
                'echelon_id' => 7,
                'available' => 9,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 136,
                'echelon_id' => 8,
                'available' => 6,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 136,
                'echelon_id' => 10,
                'available' => 4,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'position_id' => 136,
                'echelon_id' => 12,
                'available' => 4,
                'vertical_order' => 1,
                'horizontal_order' => 6,
            ],
            [
                'position_id' => 200,
                'echelon_id' => 7,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 200,
                'echelon_id' => 8,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 201,
                'echelon_id' => 7,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 201,
                'echelon_id' => 8,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 201,
                'echelon_id' => 10,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 201,
                'echelon_id' => 11,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'position_id' => 201,
                'echelon_id' => 12,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'position_id' => 202,
                'echelon_id' => 6,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 202,
                'echelon_id' => 7,
                'available' => 4,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 202,
                'echelon_id' => 8,
                'available' => 4,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 142,
                'echelon_id' => 6,
                'available' => 5,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 142,
                'echelon_id' => 7,
                'available' => 13,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 142,
                'echelon_id' => 8,
                'available' => 6,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 203,
                'echelon_id' => 6,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 203,
                'echelon_id' => 7,
                'available' => 4,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 203,
                'echelon_id' => 8,
                'available' => 3,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 204,
                'echelon_id' => 7,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 204,
                'echelon_id' => 8,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 204,
                'echelon_id' => 10,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 204,
                'echelon_id' => 11,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'position_id' => 204,
                'echelon_id' => 12,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'position_id' => 147,
                'echelon_id' => 6,
                'available' => 3,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 147,
                'echelon_id' => 7,
                'available' => 4,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 147,
                'echelon_id' => 8,
                'available' => 4,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 206,
                'echelon_id' => 6,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 206,
                'echelon_id' => 7,
                'available' => 5,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 206,
                'echelon_id' => 8,
                'available' => 5,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 207,
                'echelon_id' => 6,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 150,
                'echelon_id' => 7,
                'available' => 5,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 150,
                'echelon_id' => 8,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 150,
                'echelon_id' => 10,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 150,
                'echelon_id' => 11,
                'available' => 4,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'position_id' => 150,
                'echelon_id' => 12,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'position_id' => 158,
                'echelon_id' => 8,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 158,
                'echelon_id' => 10,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 158,
                'echelon_id' => 11,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 158,
                'echelon_id' => 12,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'position_id' => 162,
                'echelon_id' => 6,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 162,
                'echelon_id' => 7,
                'available' => 6,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 162,
                'echelon_id' => 8,
                'available' => 6,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 205,
                'echelon_id' => 10,
                'available' => 4,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 205,
                'echelon_id' => 11,
                'available' => 7,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 205,
                'echelon_id' => 12,
                'available' => 6,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 208,
                'echelon_id' => 10,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 208,
                'echelon_id' => 11,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 208,
                'echelon_id' => 12,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],

            //jabatan fungsional
            [
                'position_id' => 2,
                'echelon_id' => 1,
                'available' => 1,
                'vertical_order' => 2,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 38,
                'echelon_id' => 1,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 39,
                'echelon_id' => 1,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 40,
                'echelon_id' => 1,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'position_id' => 42,
                'echelon_id' => 2,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 43,
                'echelon_id' => 2,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 44,
                'echelon_id' => 2,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'position_id' => 46,
                'echelon_id' => 4,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 50,
                'echelon_id' => 4,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 54,
                'echelon_id' => 3,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 59,
                'echelon_id' => 2,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 60,
                'echelon_id' => 2,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 61,
                'echelon_id' => 2,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'position_id' => 63,
                'echelon_id' => 4,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 67,
                'echelon_id' => 4,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 70,
                'echelon_id' => 3,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 75,
                'echelon_id' => 2,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 76,
                'echelon_id' => 2,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 77,
                'echelon_id' => 2,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'position_id' => 78,
                'echelon_id' => 2,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'position_id' => 80,
                'echelon_id' => 4,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 85,
                'echelon_id' => 4,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 90,
                'echelon_id' => 4,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 94,
                'echelon_id' => 3, //previously was 4
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 97,
                'echelon_id' => 2,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 98,
                'echelon_id' => 2,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 99,
                'echelon_id' => 2,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 100,
                'echelon_id' => 2,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'position_id' => 101,
                'echelon_id' => 2,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'position_id' => 104,
                'echelon_id' => 3,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 105,
                'echelon_id' => 3,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'position_id' => 106,
                'echelon_id' => 3,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'position_id' => 107,
                'echelon_id' => 4,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 108,
                'echelon_id' => 4,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 109,
                'echelon_id' => 4,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 110,
                'echelon_id' => 9,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 111,
                'echelon_id' => 9,
                'available' => 12,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 112,
                'echelon_id' => 9,
                'available' => 4,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 113,
                'echelon_id' => 9,
                'available' => 11,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 114,
                'echelon_id' => 9,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 116,
                'echelon_id' => 9,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 117,
                'echelon_id' => 4,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 118,
                'echelon_id' => 4,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 119,
                'echelon_id' => 4,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 120,
                'echelon_id' => 9,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 121,
                'echelon_id' => 9,
                'available' => 6,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 124,
                'echelon_id' => 9,
                'available' => 5,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 125,
                'echelon_id' => 9,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 126,
                'echelon_id' => 9,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 127,
                'echelon_id' => 9,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 128,
                'echelon_id' => 4,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 129,
                'echelon_id' => 4,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 130,
                'echelon_id' => 4,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 132,
                'echelon_id' => 9,
                'available' => 3,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 134,
                'echelon_id' => 9,
                'available' => 3,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 135,
                'echelon_id' => 9,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 139,
                'echelon_id' => 9,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 7,
            ],
            [
                'position_id' => 140,
                'echelon_id' => 9,
                'available' => 6,
                'vertical_order' => 1,
                'horizontal_order' => 8,
            ],
            [
                'position_id' => 141,
                'echelon_id' => 9,
                'available' => 4,
                'vertical_order' => 1,
                'horizontal_order' => 9,
            ],
            [
                'position_id' => 145,
                'echelon_id' => 9,
                'available' => 4,
                'vertical_order' => 1,
                'horizontal_order' => 6,
            ],
            [
                'position_id' => 146,
                'echelon_id' => 9,
                'available' => 3,
                'vertical_order' => 1,
                'horizontal_order' => 7,
            ],
            [
                'position_id' => 149,
                'echelon_id' => 3,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'position_id' => 151,
                'echelon_id' => 4,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 152,
                'echelon_id' => 9,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 153,
                'echelon_id' => 9,
                'available' => 7,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'position_id' => 154,
                'echelon_id' => 9,
                'available' => 4,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'position_id' => 157,
                'echelon_id' => 9,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 159,
                'echelon_id' => 3,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 160,
                'echelon_id' => 3,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 161,
                'echelon_id' => 3,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'position_id' => 163,
                'echelon_id' => 10,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 163,
                'echelon_id' => 11,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 163,
                'echelon_id' => 12,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 164,
                'echelon_id' => 9,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 166,
                'echelon_id' => 9,
                'available' => 6,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'position_id' => 167,
                'echelon_id' => 4,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 168,
                'echelon_id' => 4,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 169,
                'echelon_id' => 4,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 170,
                'echelon_id' => 9,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 172,
                'echelon_id' => 9,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 174,
                'echelon_id' => 9,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 176,
                'echelon_id' => 9,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 178,
                'echelon_id' => 4,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 179,
                'echelon_id' => 4,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 180,
                'echelon_id' => 4,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 183,
                'echelon_id' => 9,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 184,
                'echelon_id' => 9,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 185,
                'echelon_id' => 9,
                'available' => 11,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 187,
                'echelon_id' => 9,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 188,
                'echelon_id' => 9,
                'available' => 15,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 189,
                'echelon_id' => 7,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 191,
                'echelon_id' => 8,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 192,
                'echelon_id' => 7,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'position_id' => 199,
                'echelon_id' => 9,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 182,
                'echelon_id' => 9,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 211,
                'echelon_id' => 12,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 213,
                'echelon_id' => 4,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 214,
                'echelon_id' => 6,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 215,
                'echelon_id' => 6,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'position_id' => 216,
                'echelon_id' => 10,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'position_id' => 217,
                'echelon_id' => 11,
                'available' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 6,
            ],
            [
                'position_id' => 218,
                'echelon_id' => 12,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 7,
            ],
            [
                'position_id' => 219,
                'echelon_id' => 9,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 8,
            ],
            [
                'position_id' => 37,
                'echelon_id' => 1,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 232,
                'echelon_id' => 7,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'position_id' => 232,
                'echelon_id' => 8,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'position_id' => 232,
                'echelon_id' => 10,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'position_id' => 232,
                'echelon_id' => 11,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'position_id' => 232,
                'echelon_id' => 12,
                'available' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
        ];

        DB::table('position_echelons')->insertTs($positionEchelons);
    }
}
