<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PositionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('positions')->delete();
        $positions = [
            [
                'id' => 1,
                'parent_id' => null,
                'name' => 'Staff Khusus Wakil Presiden',
                'available' => 0,
                'filled' => 0,
                'children' => 10,
                'type' => 1,
                'entity' => 2,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 2,
                'parent_id' => null,
                'name' => 'Kepala Sekretariat Wakil Presiden',
                'available' => 1,
                'filled' => 1,
                'children' => 4,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 2,
                'horizontal_order' => 1,
            ],
            [
                'id' => 3,
                'parent_id' => null,
                'name' => 'Perbantuan Non ASN',
                'available' => 1,
                'filled' => 1,
                'children' => 4,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 2,
                'horizontal_order' => 1,
            ],
            [
                'id' => 4,
                'parent_id' => null,
                'name' => 'Pejabat Kemensetneg yang Diperbantukan di Sekretariat Wakil Presiden',
                'available' => 0,
                'filled' => 0,
                'children' => 4,
                'type' => 1,
                'entity' => 2,
                'vertical_order' => 3,
                'horizontal_order' => 1,
            ],
            [
                'id' => 5,
                'parent_id' => 1,
                'name' => 'Staff Khusus Wakil Presiden (Bidang Umum)',
                'available' => 1,
                'filled' => 1,
                'children' => 2,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 6,
                'parent_id' => 1,
                'name' => 'Staff Khusus Wakil Presiden (Bidang Komunikasi dan Informasi)',
                'available' => 1,
                'filled' => 1,
                'children' => 2,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 7,
                'parent_id' => 1,
                'name' => 'Staff Khusus Wakil Presiden (Bidang Hukum)',
                'available' => 1,
                'filled' => 1,
                'children' => 2,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 8,
                'parent_id' => 1,
                'name' => 'Staff Khusus Wakil Presiden (Bidang Politik dan Hubungan Antar Lembaga)',
                'available' => 1,
                'filled' => 1,
                'children' => 2,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'id' => 9,
                'parent_id' => 1,
                'name' => 'Staff Khusus Wakil Presiden (Bidang Ekonomi dan Keuangan)',
                'available' => 1,
                'filled' => 1,
                'children' => 2,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'id' => 10,
                'parent_id' => 1,
                'name' => 'Staff Khusus Wakil Presiden (Bidang Infrastruktur dan Investasi)',
                'available' => 1,
                'filled' => 1,
                'children' => 2,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 6,
            ],
            [
                'id' => 11,
                'parent_id' => 1,
                'name' => 'Staff Khusus Wakil Presiden (Bidang Reformasi Birokrasi)',
                'available' => 1,
                'filled' => 1,
                'children' => 2,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 7,
            ],
            [
                'id' => 12,
                'parent_id' => 1,
                'name' => 'Staff Khusus Wakil Presiden (Bidang Penanggulangan Kemiskinan dan Otonomi Daerah)',
                'available' => 1,
                'filled' => 1,
                'children' => 2,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 8,
            ],
            [
                'id' => 13,
                'parent_id' => 1,
                'name' => 'Staff Khusus Wakil Presiden',
                'available' => 1,
                'filled' => 1,
                'children' => 2,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 9,
            ],
            [
                'id' => 14,
                'parent_id' => 1,
                'name' => 'Staff Khusus Wakil Presiden',
                'available' => 1,
                'filled' => 1,
                'children' => 2,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 10,
            ],
            [
                'id' => 15,
                'parent_id' => 5,
                'name' => 'Asisten Staff Khusus Wakil Presiden (Bidang Umum)',
                'available' => 2,
                'filled' => 2,
                'children' => 0,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 16,
                'parent_id' => 6,
                'name' => 'Asisten Staff Khusus Wakil Presiden (Bidang Komunikasi dan Informasi)',
                'available' => 2,
                'filled' => 2,
                'children' => 0,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 17,
                'parent_id' => 7,
                'name' => 'Asisten Staff Khusus Wakil Presiden (Bidang Hukum)',
                'available' => 2,
                'filled' => 2,
                'children' => 0,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 18,
                'parent_id' => 8,
                'name' => 'Asisten Staff Khusus Wakil Presiden (Bidang Politik dan Hubungan Antar Lembaga)',
                'available' => 2,
                'filled' => 2,
                'children' => 0,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 19,
                'parent_id' => 9,
                'name' => 'Asisten Staff Khusus Wakil Presiden (Bidang Ekonomi dan Keuangan)',
                'available' => 2,
                'filled' => 2,
                'children' => 0,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 20,
                'parent_id' => 10,
                'name' => 'Asisten Staff Khusus Wakil Presiden (Bidang Infrastruktur dan Investasi)',
                'available' => 2,
                'filled' => 2,
                'children' => 0,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 21,
                'parent_id' => 11,
                'name' => 'Asisten Staff Khusus Wakil Presiden (Bidang Reformasi Birokrasi)',
                'available' => 2,
                'filled' => 2,
                'children' => 0,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 22,
                'parent_id' => 12,
                'name' => 'Asisten Staff Khusus Wakil Presiden (Bidang Penanggulangan Kemiskinan dan Otonomi Daerah)',
                'available' => 2,
                'filled' => 2,
                'children' => 0,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 23,
                'parent_id' => 13,
                'name' => 'Asisten Staff Khusus Wakil Presiden',
                'available' => 2,
                'filled' => 2,
                'children' => 0,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 24,
                'parent_id' => 14,
                'name' => 'Asisten Staff Khusus Wakil Presiden',
                'available' => 1,
                'filled' => 1,
                'children' => 6,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 25,
                'parent_id' => 15,
                'name' => 'Asisten Staff Khusus Wakil Presiden',
                'available' => 1,
                'filled' => 1,
                'children' => 0,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 26,
                'parent_id' => 24,
                'name' => 'Pembantu Asisten Staff Khusus Wakil Presiden (BANAS I)',
                'available' => 1,
                'filled' => 1,
                'children' => 0,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 27,
                'parent_id' => 24,
                'name' => 'Pembantu Asisten Staff Khusus Wakil Presiden (BANAS II)',
                'available' => 1,
                'filled' => 1,
                'children' => 0,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 28,
                'parent_id' => 24,
                'name' => 'Pembantu Asisten Staff Khusus Wakil Presiden (BANAS III)',
                'available' => 1,
                'filled' => 1,
                'children' => 0,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 29,
                'parent_id' => 24,
                'name' => 'Pembantu Asisten Staff Khusus Wakil Presiden (BANAS IV)',
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'id' => 30,
                'parent_id' => 24,
                'name' => 'Pembantu Asisten Staff Khusus Wakil Presiden (BANAS V)',
                'available' => 1,
                'filled' => 1,
                'children' => 0,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'id' => 31,
                'parent_id' => 24,
                'name' => 'Pembantu Asisten Staff Khusus Wakil Presiden (BANAS VI)',
                'available' => 1,
                'filled' => 1,
                'children' => 0,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 6,
            ],
            [
                'id' => 32,
                'parent_id' => 3,
                'name' => 'Ajudan Wakil Presiden',
                'available' => 4,
                'filled' => 4,
                'children' => 0,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 33,
                'parent_id' => 3,
                'name' => 'Ajudan Istri Wakil Presiden',
                'available' => 4,
                'filled' => 4,
                'children' => 0,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 34,
                'parent_id' => 3,
                'name' => 'Dokter Pribadi Wakil Presiden',
                'available' => 4,
                'filled' => 4,
                'children' => 0,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 35,
                'parent_id' => 3,
                'name' => 'Anggota Tim Ahli Wakil Presiden',
                'available' => 12,
                'filled' => 12,
                'children' => 0,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'id' => 36,
                'parent_id' => 3,
                'name' => 'Staff Pendukung Wakil Presiden',
                'available' => 2,
                'filled' => 2,
                'children' => 0,
                'type' => 1,
                'entity' => 1,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
        ];
        DB::table('positions')->insertTs($positions);
    }
}
