<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PositionEchelonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('position_echelons')->delete();

        $positionEchelons = [
            [
                'id' => 1,
                'position_id' => 41,
                'echelon_id' => 5,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 2,
                'position_id' => 45,
                'echelon_id' => 6,
                'available' => 3,
                'filled' => 2,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 3,
                'position_id' => 45,
                'echelon_id' => 7,
                'available' => 5,
                'filled' => 5,
                'children' => 0,
                'vertical_order' => 2,
                'horizontal_order' => 2,
            ],
            [
                'id' => 4,
                'position_id' => 45,
                'echelon_id' => 8,
                'available' => 2,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 3,
                'horizontal_order' => 3,
            ],
            [
                'id' => 5,
                'position_id' => 193,
                'echelon_id' => 7,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 6,
                'position_id' => 47,
                'echelon_id' => 7,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 7,
                'position_id' => 47,
                'echelon_id' => 8,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 8,
                'position_id' => 47,
                'echelon_id' => 10,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 9,
                'position_id' => 47,
                'echelon_id' => 11,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'id' => 10,
                'position_id' => 47,
                'echelon_id' => 12,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'id' => 11,
                'position_id' => 49,
                'echelon_id' => 6,
                'available' => 3,
                'filled' => 2,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 12,
                'position_id' => 49,
                'echelon_id' => 7,
                'available' => 4,
                'filled' => 3,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 13,
                'position_id' => 49,
                'echelon_id' => 8,
                'available' => 2,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 14,
                'position_id' => 194,
                'echelon_id' => 7,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 15,
                'position_id' => 51,
                'echelon_id' => 8,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 16,
                'position_id' => 51,
                'echelon_id' => 10,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 17,
                'position_id' => 51,
                'echelon_id' => 11,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 18,
                'position_id' => 51,
                'echelon_id' => 12,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'id' => 19,
                'position_id' => 53,
                'echelon_id' => 6,
                'available' => 3,
                'filled' => 3,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 20,
                'position_id' => 53,
                'echelon_id' => 7,
                'available' => 4,
                'filled' => 2,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 21,
                'position_id' => 53,
                'echelon_id' => 8,
                'available' => 2,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 22,
                'position_id' => 55,
                'echelon_id' => 7,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 23,
                'position_id' => 55,
                'echelon_id' => 8,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 24,
                'position_id' => 55,
                'echelon_id' => 10,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 25,
                'position_id' => 55,
                'echelon_id' => 11,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'id' => 26,
                'position_id' => 55,
                'echelon_id' => 12,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'id' => 27,
                'position_id' => 58,
                'echelon_id' => 5,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 28,
                'position_id' => 62,
                'echelon_id' => 6,
                'available' => 3,
                'filled' => 1,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 29,
                'position_id' => 62,
                'echelon_id' => 7,
                'available' => 4,
                'filled' => 3,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 30,
                'position_id' => 62,
                'echelon_id' => 8,
                'available' => 2,
                'filled' => 1,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 31,
                'position_id' => 195,
                'echelon_id' => 7,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 32,
                'position_id' => 64,
                'echelon_id' => 8,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 33,
                'position_id' => 64,
                'echelon_id' => 10,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 34,
                'position_id' => 64,
                'echelon_id' => 11,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 35,
                'position_id' => 64,
                'echelon_id' => 12,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'id' => 36,
                'position_id' => 66,
                'echelon_id' => 6,
                'available' => 3,
                'filled' => 3,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 37,
                'position_id' => 66,
                'echelon_id' => 7,
                'available' => 4,
                'filled' => 4,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 38,
                'position_id' => 66,
                'echelon_id' => 8,
                'available' => 2,
                'filled' => 1,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 39,
                'position_id' => 196,
                'echelon_id' => 7,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 40,
                'position_id' => 69,
                'echelon_id' => 6,
                'available' => 3,
                'filled' => 1,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 41,
                'position_id' => 69,
                'echelon_id' => 7,
                'available' => 4,
                'filled' => 4,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 42,
                'position_id' => 69,
                'echelon_id' => 8,
                'available' => 2,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 43,
                'position_id' => 71,
                'echelon_id' => 7,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 44,
                'position_id' => 71,
                'echelon_id' => 8,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 45,
                'position_id' => 71,
                'echelon_id' => 10,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 46,
                'position_id' => 71,
                'echelon_id' => 11,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'id' => 47,
                'position_id' => 71,
                'echelon_id' => 12,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'id' => 48,
                'position_id' => 74,
                'echelon_id' => 5,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 49,
                'position_id' => 79,
                'echelon_id' => 6,
                'available' => 3,
                'filled' => 2,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 50,
                'position_id' => 79,
                'echelon_id' => 7,
                'available' => 4,
                'filled' => 4,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 51,
                'position_id' => 79,
                'echelon_id' => 8,
                'available' => 2,
                'filled' => 1,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 52,
                'position_id' => 197,
                'echelon_id' => 7,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 53,
                'position_id' => 82,
                'echelon_id' => 8,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 54,
                'position_id' => 82,
                'echelon_id' => 10,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 55,
                'position_id' => 82,
                'echelon_id' => 11,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 56,
                'position_id' => 82,
                'echelon_id' => 12,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'id' => 57,
                'position_id' => 84,
                'echelon_id' => 6,
                'available' => 3,
                'filled' => 2,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 58,
                'position_id' => 84,
                'echelon_id' => 7,
                'available' => 4,
                'filled' => 2,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 59,
                'position_id' => 84,
                'echelon_id' => 8,
                'available' => 2,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 60,
                'position_id' => 198,
                'echelon_id' => 7,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 61,
                'position_id' => 87,
                'echelon_id' => 8,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 62,
                'position_id' => 87,
                'echelon_id' => 10,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 63,
                'position_id' => 87,
                'echelon_id' => 11,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 64,
                'position_id' => 87,
                'echelon_id' => 12,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'id' => 65,
                'position_id' => 89,
                'echelon_id' => 6,
                'available' => 3,
                'filled' => 3,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 66,
                'position_id' => 89,
                'echelon_id' => 7,
                'available' => 4,
                'filled' => 3,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 67,
                'position_id' => 89,
                'echelon_id' => 8,
                'available' => 2,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 68,
                'position_id' => 199,
                'echelon_id' => 7,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 69,
                'position_id' => 91,
                'echelon_id' => 8,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 70,
                'position_id' => 91,
                'echelon_id' => 10,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 71,
                'position_id' => 91,
                'echelon_id' => 11,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 72,
                'position_id' => 91,
                'echelon_id' => 12,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'id' => 73,
                'position_id' => 93,
                'echelon_id' => 6,
                'available' => 3,
                'filled' => 2,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 74,
                'position_id' => 93,
                'echelon_id' => 7,
                'available' => 4,
                'filled' => 2,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 75,
                'position_id' => 93,
                'echelon_id' => 8,
                'available' => 2,
                'filled' => 1,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 76,
                'position_id' => 95,
                'echelon_id' => 7,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 77,
                'position_id' => 95,
                'echelon_id' => 8,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 78,
                'position_id' => 95,
                'echelon_id' => 10,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 79,
                'position_id' => 95,
                'echelon_id' => 11,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'id' => 80,
                'position_id' => 95,
                'echelon_id' => 12,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'id' => 81,
                'position_id' => 102,
                'echelon_id' => 7,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 82,
                'position_id' => 102,
                'echelon_id' => 8,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 83,
                'position_id' => 102,
                'echelon_id' => 11,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 84,
                'position_id' => 102,
                'echelon_id' => 12,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'id' => 85,
                'position_id' => 103,
                'echelon_id' => 6,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 86,
                'position_id' => 136,
                'echelon_id' => 6,
                'available' => 4,
                'filled' => 3,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 87,
                'position_id' => 136,
                'echelon_id' => 7,
                'available' => 9,
                'filled' => 8,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 88,
                'position_id' => 136,
                'echelon_id' => 8,
                'available' => 6,
                'filled' => 2,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 89,
                'position_id' => 136,
                'echelon_id' => 10,
                'available' => 4,
                'filled' => 1,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'id' => 90,
                'position_id' => 136,
                'echelon_id' => 11,
                'available' => 4,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'id' => 91,
                'position_id' => 136,
                'echelon_id' => 12,
                'available' => 4,
                'filled' => 2,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 6,
            ],
            [
                'id' => 92,
                'position_id' => 200,
                'echelon_id' => 7,
                'available' => 2,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 93,
                'position_id' => 200,
                'echelon_id' => 8,
                'available' => 2,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 94,
                'position_id' => 201,
                'echelon_id' => 7,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 95,
                'position_id' => 201,
                'echelon_id' => 8,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 96,
                'position_id' => 201,
                'echelon_id' => 10,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 97,
                'position_id' => 201,
                'echelon_id' => 11,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'id' => 98,
                'position_id' => 201,
                'echelon_id' => 12,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'id' => 99,
                'position_id' => 202,
                'echelon_id' => 6,
                'available' => 2,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 100,
                'position_id' => 202,
                'echelon_id' => 7,
                'available' => 4,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 101,
                'position_id' => 202,
                'echelon_id' => 8,
                'available' => 4,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 102,
                'position_id' => 142,
                'echelon_id' => 6,
                'available' => 5,
                'filled' => 5,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 103,
                'position_id' => 142,
                'echelon_id' => 7,
                'available' => 9,
                'filled' => 9,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 104,
                'position_id' => 142,
                'echelon_id' => 8,
                'available' => 6,
                'filled' => 2,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 105,
                'position_id' => 203,
                'echelon_id' => 6,
                'available' => 2,
                'filled' => 2,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 106,
                'position_id' => 203,
                'echelon_id' => 7,
                'available' => 4,
                'filled' => 2,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 107,
                'position_id' => 203,
                'echelon_id' => 8,
                'available' => 3,
                'filled' => 1,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 108,
                'position_id' => 204,
                'echelon_id' => 7,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 109,
                'position_id' => 204,
                'echelon_id' => 8,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 110,
                'position_id' => 204,
                'echelon_id' => 10,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 111,
                'position_id' => 204,
                'echelon_id' => 11,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'id' => 112,
                'position_id' => 204,
                'echelon_id' => 12,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'id' => 113,
                'position_id' => 147,
                'echelon_id' => 6,
                'available' => 1,
                'filled' => 1,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 114,
                'position_id' => 147,
                'echelon_id' => 7,
                'available' => 4,
                'filled' => 4,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 115,
                'position_id' => 147,
                'echelon_id' => 8,
                'available' => 4,
                'filled' => 1,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 116,
                'position_id' => 206,
                'echelon_id' => 6,
                'available' => 1,
                'filled' => 1,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 117,
                'position_id' => 206,
                'echelon_id' => 7,
                'available' => 4,
                'filled' => 4,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 118,
                'position_id' => 206,
                'echelon_id' => 8,
                'available' => 5,
                'filled' => 1,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 119,
                'position_id' => 207,
                'echelon_id' => 6,
                'available' => 2,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 120,
                'position_id' => 150,
                'echelon_id' => 7,
                'available' => 5,
                'filled' => 3,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 121,
                'position_id' => 150,
                'echelon_id' => 8,
                'available' => 2,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 122,
                'position_id' => 150,
                'echelon_id' => 10,
                'available' => 2,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 123,
                'position_id' => 150,
                'echelon_id' => 11,
                'available' => 3,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'id' => 124,
                'position_id' => 150,
                'echelon_id' => 12,
                'available' => 2,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 5,
            ],
            [
                'id' => 125,
                'position_id' => 158,
                'echelon_id' => 8,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 126,
                'position_id' => 158,
                'echelon_id' => 10,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 127,
                'position_id' => 158,
                'echelon_id' => 11,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 128,
                'position_id' => 158,
                'echelon_id' => 12,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 4,
            ],
            [
                'id' => 129,
                'position_id' => 162,
                'echelon_id' => 6,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 130,
                'position_id' => 162,
                'echelon_id' => 7,
                'available' => 6,
                'filled' => 6,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 131,
                'position_id' => 162,
                'echelon_id' => 8,
                'available' => 1,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 132,
                'position_id' => 205,
                'echelon_id' => 10,
                'available' => 4,
                'filled' => 2,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 133,
                'position_id' => 205,
                'echelon_id' => 11,
                'available' => 7,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 134,
                'position_id' => 205,
                'echelon_id' => 12,
                'available' => 5,
                'filled' => 1,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
            [
                'id' => 135,
                'position_id' => 208,
                'echelon_id' => 10,
                'available' => 3,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 1,
            ],
            [
                'id' => 136,
                'position_id' => 208,
                'echelon_id' => 11,
                'available' => 3,
                'filled' => 0,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 2,
            ],
            [
                'id' => 137,
                'position_id' => 208,
                'echelon_id' => 12,
                'available' => 2,
                'filled' => 1,
                'children' => 0,
                'vertical_order' => 1,
                'horizontal_order' => 3,
            ],
        ];

        DB::table('position_echelons')->insertTs($positionEchelons);
    }
}
