version: "3.9"

services:
    simdatuk-api_app:
        build:
            context: .
            dockerfile: Dockerfile

        image: simdatuk-api:latest
        container_name: swp_simdatuk-api

        restart: unless-stopped

        networks:
            - app-network

        environment:
            APP_ENV: local
            APP_DEBUG: true
            APP_URL: http://10.1.53.220:8008
            APP_KEY: base64:Q9vB4vM3Lh5dRp7Kj2Nx8Yw1Fz6GtUc0Pm3JqVe5AsI=
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: SWP_simdatuk
            DB_USERNAME: UserSwp001
            DB_PASSWORD: "PassSwp2026#"
networks:
    app-network:
        external: true
